version: '3'
services:
    ethereum-monitor:
        hostname: ethereum-monitor
        container_name: ethereum-monitor
        image: tjanson/go-ethereum:netstats
        command: ["/bin/sh", "-c", "npm start > netstats.log 2>&1"]
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            WS_SECRET: 'eth-net-stats-secret'
        ports:
            - '3000:3000'
        networks:
            - las2peernet
    ethereum-boot:
        hostname: ethereum-boot
        container_name: ethereum-boot
        depends_on: 
           - ethereum-monitor
        image: tjanson/go-ethereum:monitored-client
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            ETHEREUM_MONITOR: ethereum-monitor:3000
            GETH_VERBOSITY: 1
        ports:
            - '30303'
            - '30303/udp'
            - '8545:8545'
        networks:
            - las2peernet
    las2peer-boot:
        hostname: las2peer-boot
        container_name: las2peer-boot
        depends_on: 
            - ethereum-boot
        image: rwthacis/las2peer:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: none # clean recovery not yet implemented
        environment:
            LAS2PEER_ETH_HOST: ethereum-boot:8545
        ports:
            - '9000'
            - '9000/udp'
            - '8001'
            - '8000:8080'
        networks:
            - las2peernet   
    botmanager:
        container_name: botmanager
        hostname: botmanager
        image: socialbotmanager:latest
        depends_on: 
          - sbf-db
        environment:
           BOOTSTRAP: mobsos:9000
           DATABASE_USER: root
           DATABASE_PASSWORD: Qwertzuiop123!
           DATABASE_HOST: sbf-db
           DATABASE_PORT: 3306
        ports:
           - '9000'
           - '9000/udp'
           - '8001:8080'
        networks:
           - las2peernet
    sbf-db:
        container_name: sbf-db
        hostname: sbf-db
        image: mysql:5.7.31
        ports:
            - '3306'
        environment:
           MYSQL_ROOT_PASSWORD: Qwertzuiop123!
           MYSQL_DATABASE: SBF
        networks:
            - las2peernet   
    verification:
        container_name: verification
        hostname: verification
        image: verification:latest
        environment:
           LAS2PEER_CONFIG_ENDPOINT: las2peer-boot:8001
           LAS2PEER_BOOTSTRAP: mobsos:9000
           LAS2PEER_ETH_HOST: ethereum-boot:8545
        ports:
           - '9000'
           - '9000/udp'
           - '8003:8080'
        networks:
           - las2peernet
    las2peer:
        image: rwthacis/las2peer
        environment:
            LAS2PEER_PORT: 8090
        ports:
            - "8080:8080"
            - "8090:8090"
    moodle-data-proxy:
        image: moodle-data-proxy:develop
        environment:
            MOODLE_DOMAIN: https://moodle.tech4comp.dbis.rwth-aachen.de/
            MOODLE_TOKEN: 0f04baf3cdd5c82f55eb1a96e48eec53
            COURSE_LIST: 17
            BOOTSTRAP: las2peer:8090
    mobsos-data-processing:
        image: rwthacis/mobsos-data-processing:v1.0.0
        environment:
            LAS2PEER_PORT: 8090
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "password"
            MYSQL_HOST: db
            SEND_TO_LRS: "TRUE"
            BOOTSTRAP: las2peer:8090
    learning_locker_service:
        image: rwthacis/learning-locker-service:v1.0.1
        environment:
            LRS_AUTH_ADMIN: "Basic ZWJlOGU4ZGQ1NzU4NmI4MmJlMjA3MDFmN2VlOTg3OTFlN2RiMTUzMTo2OTZhMTlkYjVjZGExZjZjZTIwYTVlNDZjNGM3OWFlOTg4MDIxMzY3"
            LRS_CLIENT_ID: 5e272044f453590025d71fb7
            LAS2PEER_PORT: 8090
            LRS_DOMAIN: "https://lrs.tech4comp.dbis.rwth-aachen.de/"
            BOOTSTRAP: las2peer:8090
    db:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
networks:
    las2peernet:
        driver: bridge